### ISSUE TITLE
全面屏安全区域布局问题（刘海屏）

### ISSUE THREAD

**Issue by douchaoyang** [douchaoyang/blog#16]
```
safe-area-inset-top //安全区域距离顶部边界的距离 
safe-area-inset-bottom //安全距离底部边界的距离 
safe-area-inset-left //安全区域距离左边边界的距离 
safe-area-inset-right //安全区域距离右边边界的距离 
```

iOS11.0-11.2 中使用 “constant()” ，如：

`constant(safe-area-inset-top)`

iOS11.3 以上使用 “env()” ，如：

`env(safe-area-inset-top)`

而 Android 则是在 5-6.x 版本中支持，使用的是 “env()”

`env(safe-area-inset-top)`

只有在使用了元信息辅助标签的扩展下才可以更好的使用：

`<meta name='viewport' content='initial-scale=1, viewport-fit=cover'>`

使用实例：

```css
@supports (padding-bottom: constant(safe-area-inset-bottom)) {
	body, #nav-bottom {
		padding-bottom: constant(safe-area-inset-bottom);
	}
}

@supports (padding-bottom: env(safe-area-inset-bottom)) {
	body, #nav-bottom {
		padding-bottom: env(safe-area-inset-bottom);
	}
}
```
