### ISSUE TITLE
虎牙直播间只保留播放器的ADGuard用户过滤器

### ISSUE THREAD

**Issue by douchaoyang** [douchaoyang/blog#4]
在用户过滤器中添加以下规则，缩小标签页也能正常看到完整画面。
``` css
huya.com###J_mainRoom > div.room-core:nth-child(2) > div.room-core-r:last-child
huya.com###J_mainRoom > div.room-footer:last-child
huya.com#$#.room-core .room-core-l { margin: 0!important; }
huya.com#$#.sidebar-min .main-wrap { padding: 0!important; }
huya.com#$#.main-room { padding: 0!important; }
huya.com###duya-header
huya.com###root > div.ssr-wrapper > div.mod-sidebar:last-child
huya.com###J_roomHeader
huya.com###player-gift-wrap
huya.com###main_col > div.room-backToTop.j_room-backToTop:last-child
huya.com###player-ctrl-wrap
huya.com#$#.main-room { min-width: auto!important; }
```
