### ISSUE TITLE
NProgress 自定义样式(本站使用)

### ISSUE THREAD

**Issue by douchaoyang** [douchaoyang/blog#4]
```css
#nprogress {
  position: fixed;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  z-index: 2233;
  background: rgba(255, 255, 255, 0.6);
}
#nprogress .bar {
  position: absolute;
  z-index: 1;
  background: #0076ff;
}
#nprogress .spinner {
  position: absolute;
  left: 0;
  top: 0;
  right: 0;
  bottom: 0;
  margin: auto;
  width: 18px;
  height: 18px;
}
#nprogress .spinner .spinner-icon {
  border-left-color: #0076ff;
  border-top-color: #0076ff;
}
```
